version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
